services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: zssn
      POSTGRES_PASSWORD: zssn
      POSTGRES_DB: zssn_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: zzsn_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data:
